spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: strong
    password: 0efilsitrohs0
    url: jdbc:mysql://47.95.251.233:3306/bbs?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.ncu.strong.bbs.pojo

