package com.ncu.strong.bbs.po;

public class ActivityEnter {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_enter.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_enter.applicant_id
     *
     * @mbggenerated
     */
    private Integer applicantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_enter.activity_id
     *
     * @mbggenerated
     */
    private Integer activityId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_enter.id
     *
     * @return the value of activity_enter.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_enter.id
     *
     * @param id the value for activity_enter.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_enter.applicant_id
     *
     * @return the value of activity_enter.applicant_id
     *
     * @mbggenerated
     */
    public Integer getApplicantId() {
        return applicantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_enter.applicant_id
     *
     * @param applicantId the value for activity_enter.applicant_id
     *
     * @mbggenerated
     */
    public void setApplicantId(Integer applicantId) {
        this.applicantId = applicantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_enter.activity_id
     *
     * @return the value of activity_enter.activity_id
     *
     * @mbggenerated
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_enter.activity_id
     *
     * @param activityId the value for activity_enter.activity_id
     *
     * @mbggenerated
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }
}