package com.ncu.strong.bbs.dao;

import com.ncu.strong.bbs.po.Account;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface AccountMapper {

    Account selectByLoginName(String loginName);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * 注册账户
     */
    int insertAccount(Account account);

    /**
     *
     * @mbggenerated
     */
    int insertSelective(Account record);

    /**
     *通过id查询账户
     * @mbggenerated
     */
    Account selectByPrimaryKey(Integer id);

    /**
     *更新用户
     * @mbggenerated
     */
    int updateByPrimaryKey(Account record);

    /**
     * 修改密码
     * @param account
     * @return
     */
    int updatePasswordById(Account account);

    /**
     * 找回密码
     * @param account
     * @return
     */
    int updatePasswordByLoginName(Account account);
}