package com.ncu.strong.bbs.dao;

import com.ncu.strong.bbs.po.ActivityEnter;

public interface ActivityEnterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_enter
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_enter
     *
     * @mbggenerated
     */
    int insert(ActivityEnter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_enter
     *
     * @mbggenerated
     */
    int insertSelective(ActivityEnter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_enter
     *
     * @mbggenerated
     */
    ActivityEnter selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_enter
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ActivityEnter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_enter
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ActivityEnter record);
}