package com.ncu.strong.bbs.dao;

import com.ncu.strong.bbs.po.Setion;

import java.util.List;

public interface SetionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setion
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    int deleteBySetionId(Setion setion);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setion
     *
     * @mbggenerated
     */
    int insert(Setion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setion
     *
     * @mbggenerated
     */
    int insertSelective(Setion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setion
     *
     * @mbggenerated
     */
    //Setion selectByPrimaryKey(Integer id);

    Setion selectBySetionId(Integer Id);

    Setion selectByName(String name);

    List selectAllSetion();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setion
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Setion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setion
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Setion record);
}