package com.ncu.strong.bbs.dao;

import com.ncu.strong.bbs.pojo.Setion;
import com.ncu.strong.bbs.pojo.Theme;
import com.ncu.strong.bbs.pojo.User;

import java.util.List;

public interface ThemeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbggenerated
     */
    int insert(Theme record);

    List selectAllThemes();

    List selectUsersThemes(Integer userId);

    List selectBySetionId(Integer setionId);


    int deleteById(Integer id);

    int deleteByUserAccountId(Integer userId);

    int deleteBySetionId(Integer setionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbggenerated
     */
    int insertSelective(Theme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbggenerated
     */
    Theme selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Theme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Theme record);


}