package com.ncu.strong.bbs.dao;

import com.ncu.strong.bbs.po.Tweet;

import java.util.List;

public interface TweetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tweet
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tweet
     *
     * @mbggenerated
     */
    int insert(Tweet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tweet
     *
     * @mbggenerated
     */
    int insertSelective(Tweet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tweet
     *
     * @mbggenerated
     */
    Tweet selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tweet
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Tweet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tweet
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Tweet record);

    /**
     * 根据id查看某条动弹
     * @param id 动弹id
     * @return
     */
    Tweet getTweetById(Integer id);

    /**
     * 得到所有的动弹
     * @return
     */
    List getAllTweets();

}