package com.ncu.strong.bbs.dao;

import com.ncu.strong.bbs.pojo.userActivityKey;

public interface userActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_activity
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(userActivityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_activity
     *
     * @mbggenerated
     */
    int insert(userActivityKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_activity
     *
     * @mbggenerated
     */
    int insertSelective(userActivityKey record);
}