package com.ncu.strong.bbs.dao;

import com.ncu.strong.bbs.po.User;

import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbggenerated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbggenerated
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbggenerated
     */
    User selectByPrimaryKey(Integer id);

    User selectByAccountId(Integer id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(User record);

     List<User> findAllUser();

    /**
     * 得到某一用户的所有动弹
     * @param id
     * @return
     */
    User getTweetsByUser(Integer id);

    /**
     * 得到某一用户的所有问题
     * @param id
     * @return
     */
    User getQuestionsByUser(Integer id);

    /**
     * 得到某一用户的所有回答
     * @param id
     * @return
     */
    User getAnswersByUser(Integer id);

    /**
     * 查询某一用户创建的活动
     */
    User getCreateActivity(Integer id);

    /**
     * 查询某一用户参与的活动
     * @param id
     * @return
     */
    User getEnterActivity(Integer id);
}