package com.ncu.strong.bbs.pojo;

public class Setion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column setion.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column setion.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column setion.statement
     *
     * @mbggenerated
     */
    private String statement;

    private Integer postNum;
    private Integer ThemeNum;


    public Integer getPostNum() {
        return postNum;
    }

    public void setPostNum(Integer postNum) {
        this.postNum = postNum;
    }

    public Integer getThemeNum() {
        return ThemeNum;
    }

    public void setThemeNum(Integer themeNum) {
        ThemeNum = themeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column setion.id
     *
     * @return the value of setion.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column setion.id
     *
     * @param id the value for setion.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column setion.name
     *
     * @return the value of setion.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column setion.name
     *
     * @param name the value for setion.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column setion.statement
     *
     * @return the value of setion.statement
     *
     * @mbggenerated
     */
    public String getStatement() {
        return statement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column setion.statement
     *
     * @param statement the value for setion.statement
     *
     * @mbggenerated
     */
    public void setStatement(String statement) {
        this.statement = statement == null ? null : statement.trim();
    }
}