package com.ncu.strong.bbs.pojo;

import java.util.Date;

public class Theme {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column theme.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column theme.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column theme.setion_id
     *
     * @mbggenerated
     */
    private Integer setionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column theme.author_account_id
     *
     * @mbggenerated
     */
    private Integer authorAccountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column theme.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column theme.latest_time
     *
     * @mbggenerated
     */
    private Date latestTime;

    private String nickname;

    private String avatar;

    private String replyNum;

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public String getReplyNum() {
        return replyNum;
    }

    public void setReplyNum(String replyNum) {
        this.replyNum = replyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column theme.id
     *
     * @return the value of theme.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column theme.id
     *
     * @param id the value for theme.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column theme.title
     *
     * @return the value of theme.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column theme.title
     *
     * @param title the value for theme.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column theme.setion_id
     *
     * @return the value of theme.setion_id
     *
     * @mbggenerated
     */
    public Integer getSetionId() {
        return setionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column theme.setion_id
     *
     * @param setionId the value for theme.setion_id
     *
     * @mbggenerated
     */
    public void setSetionId(Integer setionId) {
        this.setionId = setionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column theme.author_account_id
     *
     * @return the value of theme.author_account_id
     *
     * @mbggenerated
     */
    public Integer getAuthorAccountId() {
        return authorAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column theme.author_account_id
     *
     * @param authorAccountId the value for theme.author_account_id
     *
     * @mbggenerated
     */
    public void setAuthorAccountId(Integer authorAccountId) {
        this.authorAccountId = authorAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column theme.create_time
     *
     * @return the value of theme.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column theme.create_time
     *
     * @param createTime the value for theme.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column theme.latest_time
     *
     * @return the value of theme.latest_time
     *
     * @mbggenerated
     */
    public Date getLatestTime() {
        return latestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column theme.latest_time
     *
     * @param latestTime the value for theme.latest_time
     *
     * @mbggenerated
     */
    public void setLatestTime(Date latestTime) {
        this.latestTime = latestTime;
    }
}