package com.ncu.strong.bbs.pojo;

import java.util.Date;
import java.util.List;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.nickname
     *
     * @mbggenerated
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.birthday
     *
     * @mbggenerated
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.gender
     *
     * @mbggenerated
     */
    private Integer gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.avatar
     *
     * @mbggenerated
     */
    private String avatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.user_account_id
     *
     * @mbggenerated
     */
    private Integer userAccountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.motto
     *
     * @mbggenerated
     */
    private String motto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.identity
     *
     * @mbggenerated
     */
    private Integer identity;

    /**
     * 用户的所有动弹
     */
    private List<Tweet> tweets;
    /**
     * 用户的所有提问
     */
    private List<Question> questions;
    /**
     * 用户的所有回答
     */
    private List answers;
    /**
     * 用户的所有创建活动
     */
    private List create;
    /**
     * 用户所参与的活动
     */
    private List enter;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.id
     *
     * @return the value of user_profile.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.id
     *
     * @param id the value for user_profile.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.nickname
     *
     * @return the value of user_profile.nickname
     *
     * @mbggenerated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.nickname
     *
     * @param nickname the value for user_profile.nickname
     *
     * @mbggenerated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.email
     *
     * @return the value of user_profile.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.email
     *
     * @param email the value for user_profile.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.birthday
     *
     * @return the value of user_profile.birthday
     *
     * @mbggenerated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.birthday
     *
     * @param birthday the value for user_profile.birthday
     *
     * @mbggenerated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.gender
     *
     * @return the value of user_profile.gender
     *
     * @mbggenerated
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.gender
     *
     * @param gender the value for user_profile.gender
     *
     * @mbggenerated
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.avatar
     *
     * @return the value of user_profile.avatar
     *
     * @mbggenerated
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.avatar
     *
     * @param avatar the value for user_profile.avatar
     *
     * @mbggenerated
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.phone
     *
     * @return the value of user_profile.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.phone
     *
     * @param phone the value for user_profile.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.user_account_id
     *
     * @return the value of user_profile.user_account_id
     *
     * @mbggenerated
     */
    public Integer getUserAccountId() {
        return userAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.user_account_id
     *
     * @param userAccountId the value for user_profile.user_account_id
     *
     * @mbggenerated
     */
    public void setUserAccountId(Integer userAccountId) {
        this.userAccountId = userAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.motto
     *
     * @return the value of user_profile.motto
     *
     * @mbggenerated
     */
    public String getMotto() {
        return motto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.motto
     *
     * @param motto the value for user_profile.motto
     *
     * @mbggenerated
     */
    public void setMotto(String motto) {
        this.motto = motto == null ? null : motto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.identity
     *
     * @return the value of user_profile.identity
     *
     * @mbggenerated
     */
    public Integer getIdentity() {
        return identity;
    }

    public void setIdentity(Integer identity) {
        this.identity = identity;
    }



    public List<Tweet> getTweets() {
        return tweets;
    }

    public void setTweets(List<Tweet> tweets) {
        this.tweets = tweets;
    }

    public List<Question> getQuestions() {
        return questions;
    }

    public void setQuestions(List<Question> questions) {
        this.questions = questions;
    }

    public List<Question> getAnswers() {
        return answers;
    }

    public void setAnswers(List<Question> answers) {
        this.answers = answers;
    }

    public List getCreate() {
        return create;
    }

    public void setCreate(List create) {
        this.create = create;
    }

    public List getEnter() {
        return enter;
    }

    public void setEnter(List enter) {
        this.enter = enter;
    }
}